site_name: LAT_Alignment 
site_url: https://simonsobs.github.io/LAT_Alignment/
theme: 
  name: material 
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
  - search
  - mkdocs-homepage-copier
  - gen-files:
      scripts:
      - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
extra:
  version:
    provider: mike
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - Home: 'index.md'
  - Coordinate Systems: 'coordinate_systems.md'
  - Panel Numbering Scheme: 'panel_numbers.md'
  - Configuration File: 'config_file.md'
  - Alignment Procedure: 'alignment_procedure.md'
  - API Reference: reference/
