mirror: "primary"
title: "M1 Tracker 20250831_2"
measurement:
  - M1_1.txt
  - M1_2.txt
  - M1_3.txt
  - M1_4.txt
  - M1_5.txt
tracker_yaml:
  - ref_1.yaml
  - ref_2.yaml
  - ref_3.yaml
  - ref_4.yaml
  - ref_5.yaml
vmax: 50
common_mode:
  thresh: 5
  cut_thresh: 5
  niters: 3
fit_adjustments: False
only_adj: False 
adj_radius: 1500
# sample_every: [2, 3]
compensate: 19.05
iqr: True
load:
  source: "tracker"
  group_dist: 10
  group_thresh: .005
align_tracker:
  plot: False
  scale: False
