mirror: "primary"
measurement: Set_34.csv 
title: "M1 LAT Set 34"
vmax: 50
load:
  doubles_dist: 3
  err_thresh: 10
common_mode:
  thresh: 5
  cut_thresh: 50
  niters: 10
fit_adjustments: False
bootstrap_from: "secondary"
