mode: optical
load:
  plot: False
  doubles_dist: 10
  err_thresh: 4
align_photo:
  plot: True
align_to: secondary 
measurement: Set_23.csv 
title: M1_to_M2_Set_23
only_adj: True
common_mode:
  thresh: 5
  cut_thresh: 10
  niters: 10
