mirror: "primary"
title: "M1 Tracker 20250828"
measurement:
  - M1_1.txt
  - M1_2.txt
  - M1_3.txt
  - M1_4.txt
  - M1_5.txt
tracker_yaml:
  - ref_1.yaml
  - ref_2.yaml
  - ref_3.yaml
  - ref_4.yaml
  - ref_5.yaml
vmax: 50
common_mode:
  thresh: 5
  cut_thresh: 50
  niters: 3
fit_adjustments: False
only_adj: False 
adj_radius: 1500
# sample_every: [0, 3]
compensate: 19.05
iqr: True
load:
  source: "tracker"
  calc_sys_err: True
  cam_transform_path: LAT_M1_Surface_0_20250828.txt
align_tracker:
  plot: False
  scale: False
