mirror: "primary"
measurement: Set_20.csv 
title: "M1 LAT Set 20"
vmax: 50
load:
  doubles_dist: 3
  err_thresh: 5
common_mode:
  thresh: 5
  cut_thresh: 50
  niters: 10
fit_adjustments: False
# bootstrap_from: "secondary"
