mirror: "secondary"
title: "M2 Tracker 20250827"
measurement:
  - M2_1.txt
  - M2_2.txt
  - M2_3.txt
  - M2_4.txt
  - M2_5.txt
tracker_yaml:
  - ref_1.yaml
  - ref_2.yaml
  - ref_3.yaml
  - ref_4.yaml
  - ref_5.yaml
vmax: 50
load:
  doubles_dist: 3
  err_thresh: 10
common_mode:
  thresh: 5
  cut_thresh: 50
  niters: 3
fit_adjustments: False
only_adj: False 
adj_radius: 1500
# sample_every: [2, 3]
compensate: 19.05
iqr: True
load:
  source: "tracker"
  group_dist: .01
align_tracker:
  plot: False
  scale: False
