mirror: "secondary"
measurement: Set_32.csv 
title: "M2 LAT Set 32"
vmax: 50
load:
  doubles_dist: 3
  err_thresh: 2
common_mode:
  thresh: 5
  cut_thresh: 10
  niters: 10
fit_adjustments: False
# bootstrap_from: "secondary"
